#!/bin/sh
#husky 0.13.4

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

load_nvm () {
  export $1=$2
  [ -s "$2/nvm.sh" ] && . $2/nvm.sh
  command_exists nvm && [ -f .nvmrc ] && nvm use
}

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}

cd .

has_hook_script prereceive || exit 0

export PATH=$PATH:/usr/local/bin:/usr/local
load_nvm BREW_NVM_DIR /usr/local/opt/nvm

load_nvm NVM_DIR /Users/chen/.nvm

command_exists npm || {
  echo >&2 "> husky - Can't find npm in PATH. Skipping prereceive script in package.json"
  exit 0
}

echo
echo "> husky - npm run -s prereceive"
echo "> husky - node `node -v`"
echo

export GIT_PARAMS="$*"
npm run -s prereceive || {
  echo
  echo "> husky - pre-receive hook failed (add --no-verify to bypass)"
  echo "> husky - to debug, use 'npm run prereceive'"
  exit 1
}
